apiVersion: v1
kind: Service
metadata:
  name: product-backend-service
spec:
  selector:
    app: product-backend
  ports:
    - protocol: TCP
      port: 8080  # Kubernetes içindeki port
      targetPort: 8080  # Pod içindeki port
      nodePort: 30080  # Minikube dışından erişilecek port
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-backend
  template:
    metadata:
      labels:
        app: product-backend
    spec:
      containers:
        - name: product-backend
          image: product-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/PRODUCT"
            - name: SPRING_DATASOURCE_USERNAME
              value: "productUser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
            - name: SPRING_LIQUIBASE_ENABLED
              value: "true"
            - name: APP_LOAD_TEST_DATA
              value: "true"
            - name: JWT_SECRET
              value: "c2VsYW1sYXJsYW5uYWJlcml5aW1pc2ludGFtYW1vaweq432ds32cxsd3235gdfwxsr23cxsdf2hgvb315v55GFsZGU"
            - name: JWT_EXPIRATION
              value: "3600000"
