apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/productdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres123"
            - name: APP_LOAD_TEST_DATA
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: APP_LOAD_TEST_DATA
            - name: SPRING_LIQUIBASE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_LIQUIBASE_ENABLED
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-updater
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-configmap-updater
subjects:
- kind: ServiceAccount
  name: backend-sa
roleRef:
  kind: Role
  name: configmap-updater
  apiGroup: rbac.authorization.k8s.io 